[package]
name = "windows-helpers"
version = "0.1.5"  # Bumps must rather be breaking than not, because `windows` crate version is user's.
description = "Helpers for the windows crate"
categories = ["development-tools::ffi", "rust-patterns"]
keywords = ["windows"]
repository = "https://github.com/Enyium/windows-helpers-rs"
documentation = "https://docs.rs/windows-helpers"
license = "MIT OR Apache-2.0"
edition = "2021"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
all-features = true

[dependencies]
# The `windows` crate is regularly updated with breaking SemVer versions, although many things affecting this crate don't change. A version range makes this crate use the version the user uses and reduce the need to hurry after the `windows` crate.
windows = { version = ">= 0.48, < 1", features = [
    "Win32_Foundation",
] }
num-traits = "0.2.17"

[features]
HANDLE_CloseHandle = ["windows/Win32_Foundation"]
HBITMAP_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HBRUSH_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HDC_DeleteDC = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HFONT_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HGDIOBJ_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HGLOBAL_GlobalFree = ["windows/Win32_Foundation"]
HICON_DestroyIcon = ["windows/Win32_Foundation", "windows/Win32_UI_WindowsAndMessaging"]
HLOCAL_LocalFree = ["windows/Win32_Foundation"]
HMENU_DestroyMenu = ["windows/Win32_Foundation", "windows/Win32_UI_WindowsAndMessaging"]
HMODULE_FreeLibrary = ["windows/Win32_Foundation"]
HPALETTE_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HPEN_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]
HRGN_DeleteObject = ["windows/Win32_Foundation", "windows/Win32_Graphics_Gdi"]

[dev-dependencies]
#TODO: WITH CARGO AUTHORS: Version here affects version above. This means, this internal dev dependency, when defined with v0.52.0, e.g., makes it impossible for users of this crate to use it with an earlier version of the `windows` crate. (Confirmed with both approaches: when obtaining this crate from crates.io, and when specifying the dependency for this crate with `path = "..."`.)
windows = { version = ">= 0.48, < 1", features = [
    "Win32_Foundation",
    "Win32_Security_Authorization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_IpHelper",
    "Win32_UI_Shell",
    "Win32_Globalization",
] }
regex = "1.10.2"
